### ISSUE TITLE
Add command intent to run stale branch cleanup on demand

### ISSUE THREAD

**Issue by ipcrm** [atomist-skills/github-branch-deletion-skill#68]
In addition to the ability to run it on a schedule.

**Comment by cdupuis** [comment]
Can you provide some more details on what you want here? Currently the skill sends a message into chat to list all stale branches. Is that what you want to trigger across all selected repositories? /cc @ipcrm

**Comment by ipcrm** [comment]
The goal would be to produce the exact same dialog we see today when the command is invoked, but only for specific repos

Scenarios:

- Invoke in DM with Atomist: you would need to provide targets.repo targets.owner (or the equivalent) so the skill knows which repo to go and run the stale branch cleanup against.  Again, providing the same dialog you see today when it is produced on a schedule
- Invoke in channel with linked repos, provide the same dialog you see on a scheduled run but only for the repo(s) linked to this channel

**Comment by cdupuis** [comment]
This is now in main.
